---
apiVersion: v1
kind: Service
metadata:
  name: postgres-metrics-svc
  namespace: monitoring
  labels:
    app: postgres-metrics
spec:
  type: ClusterIP
  selector:
    app: postgres-metrics
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
